### ISSUE TITLE
bug with slider view and arrays

### ISSUE THREAD

**Issue by dietcv** [madskjeldgaard/nodeproxygui2#48]
hey, thanks for the amazing work.

I think I found a bug when using arrays. If you use the NumberBox to insert a value, the gui does update its view and you see just a single slider instead of two for this example:

(
Ndef(\test, {
	var freqRange = \freqRange.kr([100, 100], spec: ControlSpec(20, 1000));
}).gui2;
)

**Comment by redFrik** [comment]
i can confirm this. @elgiano - you want to take a look or shall i try?

**Comment by redFrik** [comment]
fixed in https://github.com/madskjeldgaard/nodeproxygui2/pull/51
