### ISSUE TITLE
a suggestion for two features

### ISSUE THREAD

**Issue by dietcv** [madskjeldgaard/nodeproxygui2#49]
hey, 

i have a suggestion for two features which is think would be really handy, and hope they could be implemented. thanks for the awesome work:

1.) a method which takes an array of parameters as an argument, and these parameters end not up as sliders in the gui.
2.) RangeSliders + Numberboxes for arrays with size 2

thanks

**Comment by redFrik** [comment]
hi, glad to hear you like this quark

1.) good idea. i've implemented something and i believe it works. please test PR https://github.com/madskjeldgaard/nodeproxygui2/pull/50

2.) we also thought about this, but hm... unsure. even if it'd be handy and save valuable screen space, the risk is that this exception for two parameters will be more confusing than helping. and many times you do _not_ want to group two parameters. what do you other developers think?

**Comment by redFrik** [comment]
thanks again for these suggestions.

1.) is now implemented via exludeParams. and an alternative (collapsing arrays) is coming. see https://github.com/madskjeldgaard/nodeproxygui2/pull/52

2.) won't happen - at least not at this point in time.
